using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DialogueManagerStoryTelling : MonoBehaviour
{
    // Start is called before the first frame update

    PersistentStats stats;
    DataGenerator dataGen;

    [SerializeField]
    public string[] dialogosAleatoriosBasicos = 
    {
        "Não tenho tempo para conversar. Tenho muito trabalho a fazer.",
        "As cavernas mágicas são um lugar amaldiçoado. Você não deveria ir lá.",
        "O homem encapuzado é um perigo para todos nós. Ele tem poderes sombrios.",
        "Você é novo por aqui? Não se meta em encrenca.",
        "Você precisa de alguma coisa? Se não, me deixe em paz.",
        "As cavernas mágicas guardam segredos antigos. Mas também armadilhas mortais.",
        "O homem encapuzado é um mistério. Ninguém sabe quem ele é ou o que ele quer.",
        "Você parece perdido. Você sabe onde está se metendo?",
        "Você não é bem-vindo aqui. Este é um vilarejo de gente honesta e trabalhadora.",
        "As cavernas mágicas atraem muitos aventureiros. Mas poucos voltam de lá.",
        "O homem encapuzado é o líder de uma seita maligna. Eles adoram as forças das trevas.",
        "Você tem alguma coisa a ver com o homem encapuzado? Se tiver, é melhor sair daqui.",
        "As cavernas mágicas são um tesouro para os curiosos. Mas também um pesadelo para os imprudentes.",
        "O homem encapuzado está sempre rondando as cavernas mágicas. Ele procura algo lá dentro.",
        "Você veio explorar as cavernas mágicas? Você é corajoso ou louco?",
        "Tenho pouco a dizer para estrangeiros. Não confio neles.",
        "As cavernas mágicas escondem segredos antigos. Respeite sua magia e mantenha-se afastado.",
        "O homem encapuzado é um sinal de problemas iminentes. Fique alerta.",
        "Vá embora. Não precisamos de forasteiros em nosso vilarejo.",
        "As cavernas mágicas já cobraram um alto preço. Muitos foram perdidos lá dentro.",
        "Não fale comigo. Estranhos sempre causam problemas.",
        "Cuidado com as cavernas mágicas. Elas engolem os tolos que se aventuram lá.",
        "Não há lugar para estranhos em nossa comunidade. Mantenha-se afastado.",
        "As cavernas mágicas são perigosas demais. Eu não arriscaria entrar nelas.",
        "O homem encapuzado traz consigo a escuridão. Fique longe dele.",
        "Vá embora. Você não é bem-vindo aqui.",
        "As cavernas mágicas são o lar de criaturas malignas. Fique longe delas.",
        "Estrangeiros não têm lugar em nosso vilarejo. Vá embora.",
        "As cavernas mágicas são um labirinto mortal. Melhor não se perder lá dentro.",
        "Cuidado com o homem encapuzado. Ele não hesitará em causar danos.",
        "Não se aproxime das cavernas mágicas. Elas têm um poder sombrio.",
        "Você não parece daqui. Mantenha-se fora de problemas.",
        "As cavernas mágicas são uma porta para o desconhecido. E poucos sobrevivem para contar a história.",
        "O homem encapuzado é um pesadelo que assombra nossos sonhos.",
        "Vilarejos como este não são para pessoas como você. Vá embora.",
        "As cavernas mágicas estão cheias de armadilhas traiçoeiras. Não seja imprudente.",
        "O homem encapuzado é um espectro que assombra nosso vilarejo.",
        "Estrangeiros não são bem-vindos em nossa terra. Parta agora.",
        "As cavernas mágicas têm uma aura de perigo. Mantenha-se afastado delas.",
        "O homem encapuzado é um sinal de desgraça. Fique longe dele se quiser viver.",
        "Não há lugar para forasteiros aqui. Vá embora antes que algo aconteça.",
        "As cavernas mágicas são um portal para o desconhecido. E poucos retornam.",
        "O homem encapuzado é um mal que devemos evitar a todo custo.",
        "Você não é daqui. Mantenha-se afastado dos problemas.",
        "As cavernas mágicas são um enigma que poucos conseguem decifrar.",
        "O homem encapuzado traz consigo a escuridão. Fique longe dele, se puder.",
        "Vilarejos como este não são para estrangeiros. Parta agora mesmo.",
        "As cavernas mágicas são traiçoeiras. Não se arrisque sem motivo.",
        "O homem encapuzado é uma sombra que nos aterroriza.",
        "Não há espaço para estranhos em nosso vilarejo. Vá embora antes que se arrependa.",
        "As cavernas mágicas são um mundo à parte. Melhor não se aventurar lá.",
        "O homem encapuzado é um mistério que nos assombra.",
        "Estrangeiros não são bem-vindos aqui. Parta imediatamente.",
        "As cavernas mágicas são traiçoeiras. Apenas os tolos ousam entrar.",
        "O homem encapuzado traz consigo a escuridão. Fique longe se quiser sobreviver.",
        "Você não é daqui. Deveria partir antes que algo de ruim aconteça.",
        "As cavernas mágicas são um desafio que poucos conseguem superar.",
        "O homem encapuzado é uma ameaça que não podemos ignorar.",
        "Não confio em estrangeiros. Eles sempre trazem problemas.",
        "Cuidado com as cavernas mágicas. Elas escondem perigos mortais.",
        "O homem encapuzado é a personificação do mal. Não se aproxime dele.",
        "Você não é bem-vindo aqui. Saia antes que eu mude de ideia.",
        "As cavernas mágicas são traiçoeiras. Não se aventure sem motivo.",
        "O homem encapuzado é uma figura sinistra que devemos temer.",
        "Forasteiros não têm lugar em nosso vilarejo. Parta agora.",
        "As cavernas mágicas são um enigma mortal. Fique longe delas.",
        "O homem encapuzado é um demônio em forma humana. Não se envolva com ele.",
        "Não confie em estranhos. Eles sempre têm segundas intenções.",
        "Cuidado com as cavernas mágicas. Elas podem levar sua vida em um piscar de olhos.",
        "O homem encapuzado é uma ameaça que paira sobre nós.",
        "Você não é daqui. Mantenha-se afastado se quiser continuar respirando.",
        "As cavernas mágicas são um lugar proibido. Não as desafie.",
        "O homem encapuzado é uma sombra que se alimenta de medo.",
        "Não temos tempo para conversa fiada. Desapareça daqui.",
        "As cavernas mágicas são o lar de criaturas malignas. É melhor você não encontrar nenhuma delas.",
        "O homem encapuzado é o executor das trevas. Ele traz consigo a morte.",
        "Você não é bem-vindo em nosso vilarejo. Saia antes que eu chame os guardas.",
        "As cavernas mágicas são um labirinto sem saída. Não se perca lá dentro.",
        "O homem encapuzado é um mensageiro da desgraça. Não se aproxime dele.",
        "Não me incomode com suas palavras. Não tenho tempo para forasteiros.",
        "As cavernas mágicas são um lugar onde a luz não chega. Fique longe delas.",
        "O homem encapuzado é um símbolo da destruição que se aproxima.",
        "Estrangeiros não têm lugar em nosso vilarejo. Não insista.",
        "As cavernas mágicas são um abismo de mistérios. Melhor não se aventurar lá dentro.",
        "O homem encapuzado é uma abominação que não deve ser enfrentada.",
        "Não confie em estranhos. Eles só trazem problemas.",
        "Cuidado com as cavernas mágicas. Elas são traiçoeiras e podem te engolir.",
        "O homem encapuzado é um espectro que nos assombra à noite.",
        "Vilarejos como este não são para pessoas como você. Vá embora enquanto ainda pode.",
        "As cavernas mágicas são um portal para o desconhecido. E poucos retornam de lá vivos.",
        "O homem encapuzado é um sinal de problemas iminentes. Mantenha-se alerta.",
        "Não há lugar para estranhos em nosso vilarejo. Parta agora ou sofra as consequências.",
        "As cavernas mágicas já cobraram um alto preço em vidas. Não seja o próximo.",
        "Não fale comigo. Estrangeiros sempre causam problemas por aqui.",
        "Cuidado com as cavernas mágicas. Elas têm um poder sombrio que atrai os incautos.",
        "Não há espaço para estranhos em nossa comunidade. Mantenha-se afastado.",
        "As cavernas mágicas são perigosas demais. Eu não arriscaria entrar nelas, se fosse você.",
        "O homem encapuzado traz consigo a escuridão. Fique longe dele, se quiser preservar sua vida.",
        "Vá embora. Você não é bem-vindo aqui, e não temos tempo para perder com forasteiros.",
        "As cavernas mágicas são o lar de criaturas malignas e armadilhas mortais. Não vá lá.",
        "Estrangeiros não são bem-vindos em nosso vilarejo. Parta imediatamente, antes que se arrependa.",
        "As cavernas mágicas são um tesouro para os curiosos, mas também um pesadelo para os imprudentes.",
        "O homem encapuzado está sempre rondando as cavernas mágicas. Parece estar em busca de algo.",
        "Você veio explorar as cavernas mágicas? Você é corajoso ou apenas louco?",
        "As cavernas mágicas são um mistério que poucos desvendaram. Tenha cautela ao adentrá-las.",
        "O homem encapuzado é uma figura sinistra que amedronta nosso vilarejo. Evite-o a todo custo.",
        "Não confio em estrangeiros. Eles só trazem problemas e desordem.",
        "Cuidado com as cavernas mágicas. Elas escondem segredos sombrios e perigos mortais.",
        "O homem encapuzado é a personificação do mal. Não se aproxime dele, a menos que queira seu fim.",
        "Você não é bem-vindo em nosso vilarejo. Saia antes que as coisas se compliquem para o seu lado.",
        "As cavernas mágicas são um desafio para os mais valentes. Você tem o que é preciso?",
        "O homem encapuzado é uma ameaça que paira sobre nossa tranquilidade. Fique longe dele.",
        "Não há espaço para estranhos em nossa comunidade. Parta imediatamente, antes que eu mude de ideia.",
        "As cavernas mágicas são traiçoeiras. Não se aventure sem uma boa razão.",
        "O homem encapuzado é uma sombra sinistra que devemos temer. Mantenha distância dele.",
        "Você não é daqui. Deveria partir antes que cause problemas.",
        "As cavernas mágicas são um enigma que poucos conseguem decifrar. Pense bem antes de explorá-las.",
        "O homem encapuzado traz consigo a escuridão. Fique longe se quiser preservar sua sanidade.",
        "Não temos tempo para estranhos. Desapareça antes que eu me arrependa de não ter chamado os guardas.",
        "As cavernas mágicas são um labirinto sem saída. Não se perca e nem arrisque sua vida à toa.",
        "O homem encapuzado é um mensageiro da desgraça. Não se aproxime dele, a menos que queira seu fim.",
        "Não me incomode com suas palavras vazias. Não tenho paciência para lidar com estrangeiros.",
        "As cavernas mágicas são um lugar onde a luz não chega. É melhor você se manter longe.",
        "O homem encapuzado é um símbolo da destruição que se aproxima. Fuja enquanto pode.",
        "Estrangeiros não são bem-vindos em nosso vilarejo. Não insista, ou enfrentará as consequências.",
        "As cavernas mágicas são traiçoeiras. Não se aventure sem um bom motivo.",
        "O homem encapuzado é uma abominação que não deve ser enfrentada. Fique longe dele.",
        "Não confie em estranhos. Eles sempre trazem problemas e perturbações.",
        "Cuidado com as cavernas mágicas. Elas são traiçoeiras e podem te devorar sem piedade.",
        "O homem encapuzado é um espectro que assombra nossos pensamentos mais sombrios.",
        "Vilarejos como este não são para pessoas como você. Vá embora antes que seja tarde demais.",
        "As cavernas mágicas são um portal para o desconhecido. E poucos retornam de lá vivos.",
        "O homem encapuzado é um presságio de problemas iminentes. Mantenha-se alerta.",
        "Não há lugar para estranhos em nosso vilarejo. Parta agora ou sofra as consequências.",
        "As cavernas mágicas já cobraram um alto preço em vidas. Não seja o próximo a pagar.",
        "Não fale comigo. Estrangeiros sempre causam problemas por aqui.",
        "Cuidado com as cavernas mágicas. Elas têm um poder sombrio que atrai os incautos.",
        "Não há espaço para estranhos em nossa comunidade. Mantenha-se afastado.",
        "As cavernas mágicas são perigosas demais. Eu não arriscaria entrar nelas, se fosse você.",
        "O homem encapuzado traz consigo a escuridão. Fique longe dele, se quiser preservar sua vida.",
        "Vá embora. Você não é bem-vindo aqui, e não temos tempo para perder com forasteiros."
    };

    void Start()
    {

        dataGen = FindObjectOfType<DataGenerator>();
        stats = FindObjectOfType<PersistentStats>();


    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
